spring.application.name=saleappv1
server.port=8080

# Thymeleaf: tat cache khi dang phat trien de thay thay doi ngay lap tuc
spring.thymeleaf.cache=false

spring.mvc.static-path-pattern=/**
spring.web.resources.static-locations=classpath:/static/
