@startuml UseCase_SaleAppV1_Custom
left to right direction
skinparam packageStyle rectangle

actor "Khách hàng" as KH
actor "Người quản trị" as QT

rectangle "Hệ thống bán hàng" {
    usecase "UC1: Xem danh sách sản phẩm" as UC1
    usecase "UC2: Xem chi tiết sản phẩm" as UC2
    usecase "UC3: Thêm vào giỏ hàng" as UC3
    usecase "UC4: Tìm kiếm nâng cao" as UC_Search
    usecase "UC5: Đăng nhập" as UC5
    usecase "UC6: Thanh toán giỏ hàng" as UC6
    usecase "UC7: Quản lý sản phẩm" as UC7
}

KH --> UC1
KH --> UC2
KH --> UC3
KH --> UC_Search
KH --> UC6

QT --> UC5
QT --> UC7

UC6 ..> UC5 : <<include>>
UC_Search ..> UC1 : <<extend>>
@enduml
